name: ci-cd
'on':
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
permissions:
  contents: read
  packages: write
env:
  NODE_VERSION: '20'
jobs:
  validate-lint:
    name: 'Validate: lint'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
    - name: Setup Node
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    - name: Run lint
      id: lint
      run: npm ci && npm run lint
  test-test-unit-test:
    name: 'Test: test-unit-test'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
    - validate-lint
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
    - name: Setup Node
      id: setup-node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: npm
    - name: Run unit tests
      id: run-unit-tests
      run: npm test
