name: ci-cd CI
'on':
  pull_request:
    branches:
    - main
permissions:
  contents: read
  packages: write
jobs:
  validate-infra:
    name: 'Validate: Infrastructure'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
